repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-added-large-files


  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1 
    hooks:
      - id: isort

  #- repo: https://github.com/PyCQA/flake8
  #  rev: 4.0.1
  #  hooks:
  #    - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910  
    hooks:
      - id: mypy
        additional_dependencies: [types-requests] 

#  - repo: https://github.com/psf/black
#    rev: 22.1.0  
#    hooks:
#      - id: black
#        language_version: 3.11 # Specify the Python version
