FROM python:3.10

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    cmake \
    pkg-config && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /work

COPY ./utils/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt